services:
  db:
    container_name: postgres_twitch
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis_twitch
    image: redis:6.0
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
